# Generated by Django 4.0 on 2022-02-01 13:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pages/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('scheme', ckeditor_uploader.fields.RichTextUploadingField()),
                ('table', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
