# Generated by Django 4.0 on 2022-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
