# Generated by Django 4.0 on 2022-02-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_categoryy_drivers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryy',
            old_name='drivers',
            new_name='categoryyy',
        ),
    ]
