# Generated by Django 4.0 on 2022-02-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_drivers_categoryy_categoryyy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryy',
            name='categoryyy',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car_name',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Categoryy',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
