# Generated by Django 4.0 on 2022-02-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_categoryy_categoryyy_remove_driver_car_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departmentееее',
        ),
    ]
