# Generated by Django 4.0 on 2022-02-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_department_departmentееее'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmentееее',
            new_name='CentralDepartments',
        ),
    ]
