# Generated by Django 4.0 on 2022-02-03 12:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pages/')),
                ('full_name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('work_activities', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
