# Generated by Django 4.0 on 2022-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pages/')),
                ('full_name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='PreStudents',
            new_name='Enrollee',
        ),
    ]
