# Generated by Django 4.0 on 2022-02-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_internationalrelationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
