# Generated by Django 4.0 on 2022-02-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_category_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
