# Generated by Django 4.0 on 2022-03-01 05:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_newscategory_rename_category_adscategory_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adscategory',
            name='description_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adscategory',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adscategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adscategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='boss_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='boss_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='location_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='location_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='time_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centraldepartments',
            name='time_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='boss_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='boss_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='location_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='location_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='time_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='time_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='full_name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='location_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='location_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='position_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='time_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externaldepartment',
            name='time_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finans',
            name='table_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='finans',
            name='table_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='finans',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finans',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalrelationships',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='internationalrelationships',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='internationalrelationships',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalrelationships',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='full_name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='position_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='time_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='time_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='work_activities_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='work_activities_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='scheme_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='scheme_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='table_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='table_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotas',
            name='table_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='quotas',
            name='table_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='quotas',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotas',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spirtualeducation',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='spirtualeducation',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='spirtualeducation',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spirtualeducation',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
