# Generated by Django 4.0 on 2022-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_new_content_en_new_content_ru_new_content_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('about_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('about_en', models.CharField(blank=True, max_length=255, null=True)),
                ('about_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='foto/')),
            ],
            options={
                'verbose_name': 'фотографию',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='FotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('descr_ru', models.TextField(blank=True, null=True)),
                ('descr_en', models.TextField(blank=True, null=True)),
                ('descr_uz', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'категорию фотогалереи',
                'verbose_name_plural': 'Категории фотогалереи',
            },
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='adscategory',
            options={'verbose_name': 'категории объявлений', 'verbose_name_plural': 'Категории объявлений'},
        ),
        migrations.AlterModelOptions(
            name='centraldepartments',
            options={'verbose_name': 'данные о центральных отделах', 'verbose_name_plural': 'Центральные отделы'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Кафедра ДТПИ', 'verbose_name_plural': 'Кафедры ДТПИ'},
        ),
        migrations.AlterModelOptions(
            name='enrollee',
            options={'verbose_name': 'данные об абитуриентах', 'verbose_name_plural': 'Абитуриенты'},
        ),
        migrations.AlterModelOptions(
            name='externaldepartment',
            options={'verbose_name': 'данные о заочном отделении', 'verbose_name_plural': 'Заочное отделение'},
        ),
        migrations.AlterModelOptions(
            name='finans',
            options={'verbose_name': 'данные о финансовой деятельности', 'verbose_name_plural': 'Финансовая деятельность'},
        ),
        migrations.AlterModelOptions(
            name='internationalrelationships',
            options={'verbose_name': 'данные о международных отножений', 'verbose_name_plural': 'Международные отношения'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'члена руководства', 'verbose_name_plural': 'Рукаводство'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'категории новостей', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name': 'данные о программах', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quotas',
            options={'verbose_name': 'данные о квотах', 'verbose_name_plural': 'Квоты'},
        ),
        migrations.AlterModelOptions(
            name='spirtualeducation',
            options={'verbose_name': 'данные о духовном образовании', 'verbose_name_plural': 'Духовное образование'},
        ),
    ]
