# Generated by Django 4.0 on 2022-03-02 10:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_foto_fotocategory_alter_ad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='pages/')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='pages/')),
                ('boss', models.CharField(max_length=255)),
                ('boss_ru', models.CharField(max_length=255, null=True)),
                ('boss_en', models.CharField(max_length=255, null=True)),
                ('boss_uz', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('time_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('time_en', models.CharField(blank=True, max_length=255, null=True)),
                ('time_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_ru', models.CharField(max_length=255, null=True)),
                ('location_en', models.CharField(max_length=255, null=True)),
                ('location_uz', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('more', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('more_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('more_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('more_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='FacultetAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255, null=True)),
                ('position_en', models.CharField(max_length=255, null=True)),
                ('position_uz', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='facultet-admins/')),
                ('fullname', models.CharField(max_length=255)),
                ('fullname_ru', models.CharField(max_length=255, null=True)),
                ('fullname_en', models.CharField(max_length=255, null=True)),
                ('fullname_uz', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('time_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('time_en', models.CharField(blank=True, max_length=255, null=True)),
                ('time_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('location_en', models.CharField(blank=True, max_length=255, null=True)),
                ('location_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultets')),
            ],
            options={
                'verbose_name': 'администрацию факультета',
                'verbose_name_plural': 'Администрация Факультета',
            },
        ),
    ]
