# Generated by Django 4.0 on 2022-03-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_facultets_facultetadmins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultetadmins',
            old_name='admin',
            new_name='facultetAdmins',
        ),
    ]
