# Generated by Django 4.0 on 2022-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_science'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='pages/')),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'решениу',
                'verbose_name_plural': 'Решения',
            },
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='pages/')),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'устав',
                'verbose_name_plural': 'Уставы',
            },
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name': 'данние о науке', 'verbose_name_plural': 'Наука'},
        ),
    ]
