# Generated by Django 4.0 on 2022-03-03 06:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_decree_regulations_alter_science_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='pages/')),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('title2_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title2_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title2_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'verbose_name': 'данние о магистратуре',
                'verbose_name_plural': 'Магистратура',
            },
        ),
    ]
