# Generated by Django 4.0 on 2022-03-03 09:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_magistr'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fotocategory', verbose_name='Категории фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adscategory', verbose_name='Категория объявлений'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adscategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='boss',
            field=models.CharField(max_length=255, verbose_name='Глава отдела'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='boss_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава отдела'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='boss_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава отдела'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='boss_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава отдела'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='email',
            field=models.CharField(max_length=255, verbose_name='адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='location',
            field=models.CharField(max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='time_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='time_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='time_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='centraldepartments',
            name='web',
            field=models.CharField(max_length=255, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='icon',
            field=models.ImageField(upload_to='pages/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='boss',
            field=models.CharField(max_length=255, verbose_name='Глава кафедры'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='boss_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава кафедры'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='boss_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава кафедры'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='boss_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава кафедры'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='email',
            field=models.CharField(max_length=255, verbose_name='адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='icon',
            field=models.ImageField(upload_to='pages/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='location',
            field=models.CharField(max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='more',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='more_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='more_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='more_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='time',
            field=models.CharField(max_length=255, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='time_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='email',
            field=models.CharField(max_length=255, verbose_name='адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='location',
            field=models.CharField(max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='time',
            field=models.CharField(max_length=255, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='externaldepartment',
            name='time_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='email',
            field=models.CharField(max_length=255, verbose_name='адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='facultetAdmins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultets', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='fullname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='fullname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='fullname_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='image',
            field=models.ImageField(upload_to='facultet-admins/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='location_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='location_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='time_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='time_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultetadmins',
            name='time_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='boss',
            field=models.CharField(max_length=255, verbose_name='Глава Факультета'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='boss_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава Факультета'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='boss_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава Факультета'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='boss_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Глава Факультета'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='email',
            field=models.CharField(max_length=255, verbose_name='адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='icon',
            field=models.ImageField(upload_to='pages/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='location',
            field=models.CharField(max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='more',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='more_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='more_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='more_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Больше информации'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='time_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='time_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='facultets',
            name='time_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='table',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='table_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='table_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='table_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='finans',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(Описание) На фото ... '),
        ),
        migrations.AlterField(
            model_name='foto',
            name='about_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(Описание) На фото ... '),
        ),
        migrations.AlterField(
            model_name='foto',
            name='about_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(Описание) На фото ... '),
        ),
        migrations.AlterField(
            model_name='foto',
            name='about_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(Описание) На фото ... '),
        ),
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to='foto/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='descr_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='fotocategory',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='icon',
            field=models.ImageField(upload_to='pages/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internationalrelationships',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title2_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='management',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Aдрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='management',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='management',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='management',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='management',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф. И. О.'),
        ),
        migrations.AlterField(
            model_name='management',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='management',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='management',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Дослжность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='time',
            field=models.CharField(max_length=255, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='management',
            name='time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='management',
            name='time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='management',
            name='time_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='management',
            name='work_activities',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='work_activities_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='work_activities_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='management',
            name='work_activities_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newscategory', verbose_name='Категория новости'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='scheme',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Схемы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='scheme_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Схемы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='scheme_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Схемы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='scheme_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Схемы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='table',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='table_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='table_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='table_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.enrollee', verbose_name='абитуриет'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='table',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='table_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='table_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='table_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='quotas',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='icon',
            field=models.ImageField(upload_to='pages/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='science',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='science',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='science',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='science',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='science',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title2_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='science',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Излбражение'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='spirtualeducation',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
