# Generated by Django 4.0 on 2022-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_foto_foto_alter_ad_ad_alter_ad_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultets',
            name='icon',
            field=models.ImageField(upload_to='pages/', verbose_name='Главная фотка'),
        ),
    ]
